name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool pkg-config doxygen
    
    - name: Build
      run: (cd liblmdb && make -j$(nproc))

    - name: Generate XML docs
      run: doxygen $GITHUB_WORKSPACE/liblmdb/Doxyfile

    - name: Run Install
      run: (cd liblmdb && make install)

    - name: Run Tests
      run: (cd liblmdb && make test)
