name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool pkg-config doxygen
    
    - name: Build
      run: (cd liblmdb && make -j$(nproc))

    - name: Generate XML docs
      run: doxygen $GITHUB_WORKSPACE/liblmdb/Doxyfile

    - name: Run Install
      run: (cd liblmdb && make install)

    - name: Run Tests
      run: (cd liblmdb && make test)
      env:
        LD_LIBRARY_PATH: ${{ github.workspace }}/liblmdb/install/lib

    - name: Generate Docs
      run: doxygen $GITHUB_WORKSPACE/liblmdb/Doxyfile

    - name: 'ApiCov'
      uses: codesa-ai/ApiCov@v0.3.1-pre
      with:
        root_path: ${{ github.workspace }}/liblmdb
        api_key: ${{ secrets.APICOV_KEY }}
        install_path: $GITHUB_WORKSPACE/liblmdb/install
        doxygen_path: $GITHUB_WORKSPACE/liblmdb/xml        
